#!/usr/bin/env node
/**
 * Build the single-file site.
 *
 * Inlines src/engine.mjs into site/template.html at the /*__ENGINE__*\/ marker
 * and writes dist/index.html. No bundler, no dependencies, no network.
 *
 * The engine is written as ESM; the browser script tag is classic, so the
 * `export ` keyword is stripped and the module is evaluated in place. The
 * engine has no imports, so this is safe.
 *
 * Why single-file: it means the whole product is one artefact you can drop on
 * any static host, a CDN, an S3 bucket, or open from disk. It also guarantees
 * the "nothing leaves your browser" claim is structurally true — there is no
 * server to send anything to.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SITE } from './site-config.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const enginePath = path.join(root, 'src', 'engine.mjs');
const templatePath = path.join(root, 'site', 'template.html');
const outDir = path.join(root, 'dist');
const outPath = path.join(outDir, 'index.html');

const MARKER = '/*__ENGINE__*/';

function build() {
  const template = fs.readFileSync(templatePath, 'utf8');
  const engine = fs.readFileSync(enginePath, 'utf8');

  if (!template.includes(MARKER)) {
    throw new Error(`template is missing the ${MARKER} marker`);
  }
  if (/^\s*import\s/m.test(engine)) {
    throw new Error('engine.mjs must stay import-free to be inlinable');
  }

  // Convert ESM exports into plain declarations for a classic script tag.
  const inlined = engine
    .replace(/^export\s+const\s+/gm, 'const ')
    .replace(/^export\s+function\s+/gm, 'function ')
    .replace(/^export\s+\{[^}]*\};?\s*$/gm, '');

  // Belt and braces: verify nothing that looks like an export survived.
  if (/^\s*export\s/m.test(inlined)) {
    throw new Error('an export survived the transform; the inlined engine would be a syntax error');
  }

  let html = template.replace(MARKER, () => inlined);

  // Fill the origin markers. Function form so a `$` in the origin can't be
  // read as a replacement pattern.
  html = html.replaceAll('__SITE__', () => SITE);

  // An unfilled marker would ship a literal `__SITE__/` canonical link.
  if (html.includes('__SITE__')) {
    throw new Error('an __SITE__ marker survived the build');
  }

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outPath, html);

  // Social card — pre-generated by scripts/gen_og.py and committed, so the
  // npm build chain never needs Python. Copied verbatim into dist/.
  const ogSrc = path.join(root, 'site', 'og.png');
  if (fs.existsSync(ogSrc)) fs.copyFileSync(ogSrc, path.join(outDir, 'og.png'));

  const kb = (Buffer.byteLength(html) / 1024).toFixed(1);
  console.log(`built dist/index.html  (${kb} KB, single file, zero dependencies)`);
  return outPath;
}

build();

// The SEO/distribution layer is generated from the same engine, so it must be
// rebuilt whenever the site is. Generating it separately invites drift between
// what the tool computes and what the marketing pages claim.
const { execFileSync } = await import('node:child_process');
execFileSync(process.execPath, [path.join(root, 'scripts', 'gen-seo.mjs')], { cwd: root, stdio: 'inherit' });
